### ISSUE TITLE
Implement UMD compilation

### ISSUE THREAD

**Issue by adrianmcli** [adrianmcli/dev-react-component#2]
This is necessary if we want to allow the resulting component to be used as a standalone javascript library. Not everyone is using Webpack to compile their React app, so this is important to do.

### Todo

- [x] Install `webpack`, `babel-core`, `babel-loader`, `babel-preset-es2015`, `babel-preset-react`.
- [x] Install `react` and `react-dom` as devDependencies.
- [x] Add Webpack configuration files to do UMD compilation (make sure they compile to a `dist` folder).
- [x] Add `build:umd` and `build:umd:min` scripts to `package.json`.
- [x] Hook up the new build scripts to the `prepublish` script.
- [x] Make sure the `dist` folder is ignored in source control.
- [x] Test to make sure that it's all working properly.

### Example Webpack Config

This example Webpack config file may be helpful:

```js
var webpack = require('webpack');
var path = require('path');

var BUILD_DIR = path.resolve(__dirname, 'dist');
var SRC_DIR = path.resolve(__dirname, 'src');

var config = {
  devtool: 'source-map',
  entry: SRC_DIR + '/index.js',
  output: {
    path: BUILD_DIR,
    filename: 'index.js',
    libraryTarget: 'umd',
  },
  module: {
    loaders: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        query: { presets: ['es2015', 'react'] },
      },
    ],
  },
};

module.exports = config;
```

**Comment by adrianmcli** [comment]
Done.
